version: "3.8"
services:
    web:
        build:
            context: ./app/web
        volumes:
            - ./app/web/src:/var/www/html
        ports:
            - "80:80"
        networks:
            backend:
                ipv4_address: 172.16.0.2
        depends_on:
            - db

    db:
        image: mysql:5.7
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=p4ssw0rd
            - MYSQL_DATABASE=database
        volumes:
            - ./app/db:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
        networks:
            backend:
                ipv4_address: 172.16.0.3

networks:
    backend:
        ipam:
            driver: default
            config:
                - subnet: "172.16.0.0/29"
